name: Build documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  INSTANCE: 'Writerside/hi'
  DOCKER_VERSION: '243.21565'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      algolia_artifact: ${{ steps.define-ids.outputs.algolia_artifact }}
      artifact: ${{ steps.define-ids.outputs.artifact }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Define instance id and artifacts
        id: define-ids
        run: |
          INSTANCE=${INSTANCE#*/}
          INSTANCE_ID_UPPER=$(echo "$INSTANCE" | tr '[:lower:]' '[:upper:]')
          echo "INSTANCE_ID_UPPER=$INSTANCE_ID_UPPER" >> $GITHUB_ENV
          echo "ALGOLIA_ARTIFACT=algolia-indexes-$INSTANCE_ID_UPPER.zip" >> $GITHUB_ENV
          echo "ARTIFACT=webHelp$INSTANCE_ID_UPPER-all.zip" >> $GITHUB_ENV

      - name: Run JetBrains Writerside GitHub Action
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}
        env:
          INSTANCE: ${{ env.INSTANCE }}
          DOCKER_VERSION: ${{ env.DOCKER_VERSION }}
          INSTANCE_ID_UPPER: ${{ env.INSTANCE_ID_UPPER }}
          ARTIFACT: ${{ env.ARTIFACT }}
          ALGOLIA_ARTIFACT: ${{ env.ALGOLIA_ARTIFACT }}

      - name: Test existing artifacts
        run: |
          echo "Test existing artifacts"
          test -e /github/workspace/artifacts/${{ env.ARTIFACT }} && echo ${{ env.ARTIFACT }} exists
          if [ -z "$(ls -A /github/workspace/artifacts/ 2>/dev/null)" ]; then
             echo "Artifacts not found" && false
          else
             chmod 777 /github/workspace/artifacts/
             ls -la /github/workspace/artifacts/